apiVersion: v1
kind: Pod
metadata:
  name: hostpathvolmount
spec:
  containers:
  - name: hostpathvolmountcontainer  
    image: sangmeshbhure/ip_app
    ports:
    - containerPort: 80
    volumeMounts:
    - name: hostpath-vol
      mountPath: /app/volume
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /home/ubuntu/pod_data
      type: DirectoryOrCreate
