apiVersion: v1
kind: pod
metadata:
  name: hostpathvolmount
spec:
  containers:
  - name: hostpathvolmountcontainer  
    image: harshajain/ip_app
    ports:
      containerPort: 80
    volumeMounts:
    - name: hostpath-vol
      mountPath: /app/volume
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /home/ubuntu/pod_data
      type: DirectoryOrCreat
