apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: itd-k8s
  source:
    repoURL: https://github.com/sangmeshgit/k8s-commands.git
    targetRevision: main
    path: kubernates/argocd/kube_configs
  destination:
    server: https://<serverIP>:6443
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
