apiVersion: v1
kind: Pod
metadata:
  name: myconfigmappod
spec:
  containers:
    - name: ip-app
      image: harshajain/ip_app
      ports:
      - containerPort: 80
      env:
      - name: DB_URL 
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: db_url
      - name: DB_USER
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: db_user
