apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 5
  selector:
    matchLables:
      apt: tomcat
  template:
    metadata:
      labels:
        apt: tomcat
    spec:
      containers:
        - name: mycontainer
          image: harshajain/ip_app
          ports:
            - containerPort: 8080
