apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tom
  template:
    metadata:
      labels:
        app: tom
    spec:
      containers:
      - name: ip-app
        image: sangmeshbhure/ip_app
        ports:
        - containerPort: 80

