apiVersion: v1
kind: Pod
metadata:
  name: ip-app-resource-quota
spec:
  containers:
    - name: ip-app
      image: harshajain/ip_app
      ports:
        - containerPort: 80
      resources:
      limits:
        memory: "150Mi"
        cpu: "500m"
      requests:
        memory: "100Mi"
        cpu: "250m"
  priorityClassName: high-priority       
