apiVersion: v1
kind: Secret
metadata:
  name: mysecretwithpod
type: Opaque
data:
  db_url: fdfdnvijkkskd
  db_user: jvjdfknkjsnfkjf=
---
apiVersion: v1
kind: Pod
metadata:
  name: mysecretwithpodpod
spec:
  containers:
  - name: mysecretwithpodcontainer
    image: harshajain/ip_app
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      valueFrom:
        secretKeyRef:
          name: mysecretwithpod
          key: db_url
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: mysecretwithpod
          key: db_user
